source "https://rubygems.org"

# gem "bcrypt", "~> 3.1.7" # Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bootsnap", "1.18.6", require: false # Reduces boot times through caching; required in config/boot.rb
# gem "image_processing", "~> 1.2" # Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "jbuilder" # Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "kamal", "2.8.0", require: false # Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "pg", "1.6.2" # Use postgresql as the database for Active Record
gem "puma", "7.1.0" # Use the Puma web server [https://github.com/puma/puma]
# gem "rack-cors" # Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rails", "8.0.3" # Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "solid_cable", "3.0.12" # Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache", "1.0.8"
gem "solid_queue", "1.2.1"
gem "thruster", "0.1.16", require: false # Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "tzinfo-data", "2.0.6", platforms: %i[ windows jruby ] # Windows does not include zoneinfo files, so bundle the tzinfo-data gem

group :development, :test do
  gem "brakeman", "7.1.0", require: false # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "debug", "1.11.0", platforms: %i[ mri windows ], require: "debug/prelude" # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "rubocop-rails-omakase", "1.1.0", require: false # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
end
